# Generated by Django 2.0 on 2019-12-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_name',
            field=models.CharField(max_length=30, verbose_name='分类标签'),
        ),
    ]
